# Generated by Django 4.2.1 on 2023-07-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_websitemeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitemeta',
            name='about',
            field=models.TextField(max_length=5000),
        ),
    ]
